import "@styles/globals.css";
import { Inter } from "next/font/google";
import NavBar from "@components/NavBar";
import Provider from "@components/Provider";
import { Providers as UIProvider } from "@components/UIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <UIProvider>
            <main className="app">
              <NavBar />
              {children}
            </main>
          </UIProvider>
        </Provider>
      </body>
    </html>
  );
}
